### ISSUE TITLE
Win32 Desktop sample app should use ::GetClientRect() to position the Xaml window

### ISSUE THREAD

**Issue by jonverrier** [microsoft/Xaml-Islands-Samples#15]
Hi,

At lines 140 and 253 of DesktopWin32App.cpp the desktop app needs to call ::GetClientRect(). This positions the xaml island relative to the inside of the window. GetWindowRect() includes space occupied by borders, menu bar etc so the island is actually in the wrong place - this becomes apparent if you use an Island that fills the client area. 

Jon

**Comment by simonowen** [comment]
Duplicate of #8?

**Comment by jonverrier** [comment]
Yes - sorry, didn't spot that.
