### ISSUE TITLE
Questionable try-catch block in UWP application project

### ISSUE THREAD

**Issue by sylveon** [microsoft/Xaml-Islands-Samples#23]
Seriously what the heck is this

https://github.com/microsoft/Xaml-Islands-Samples/blob/7f97995841ed216e78bc6d9bd3876236e1fcbe98/Samples/Managed/UWPApplication/MainPage.xaml.cs#L11-L18

**Comment by marb2000** [comment]
This is a horrible code that I wrote? 🤦‍♀️ If so, you can punch me in the face.

**Comment by marb2000** [comment]
Fixed! @sylveon thanks for the feedback!
