### ISSUE TITLE
WPF sample does not 

### ISSUE THREAD

**Issue by ingrown** [microsoft/Xaml-Islands-Samples#27]
Sorry to bug you, but I can't build the WPF sample because the Microsoft.UI.Xaml.Controls namespace does not contain a CustomControl element. Hope to hear back.

**Comment by dephora** [comment]
#### UWPApplication project
1. Disable line 43 in MainPage.xaml (`<!--<component:CustomControl Grid.Row="1" Content="Custom Button" Margin="10,100" Height="50" Width="100" VerticalAlignment="Top" />-->`)
2. Remove reference to UILibrary (should have a warning triangle on it)

#### Solution
1. Change startup project to WAP
2. Clean / Rebuild / Run

**Comment by marb2000** [comment]
Thanks @ingrown  for letting us know, and @dephora for the help. I have removed the CustomControl from the sample. I should work now. Please, reopen it in case it doesn't.
