### ISSUE TITLE
SwapChainPanel native control crashes on unpackaged WPF Sample

### ISSUE THREAD

**Issue by marb2000** [microsoft/Xaml-Islands-Samples#6]
**STEPS**
1- Open the Standalone_Samples/WPF_Core3/WPF_XAMLIslands.sln
2- Run the sample from the WPF project
3- Press on Media tab

**Observed**: The app crashes
**Expected**: The app shows a bunch of controls including the SwapChainPanel

**Comment by jdsterli** [comment]
I am wondering of the current status of this ticket.
I have been working on a very large project using XAML Islands and this is the biggest issue for me. Dare I say I have everything else working.
More observations:
Using the Packaged Project outside of main development PC will give exception on creation of "CustomRenderer" in MediaPage.xaml.cs, in MediaPage_Loaded of type FileNotFoundException.
{"The specified module could not be found. (0x8007007E)":null}. All other Controls and Tabs seems to function correctly, but the SwapChainPanel is unique in how it is created.

I get it when using Remote Machine as target device which is assigned to another Windows 10 PC using Windows Insider Preview (same as my Dev PC).
Further launching of WAP Project from Remote PC without Visual Studio will produce same error.

I get this same error with my own project in a similar manner.

Another Observation: Side Loading the packaged project into another PC via PowerShell (created with Publish->Create App Packages...)  will have issue in that it fails to launch (or quickly closes in error I'm not sure). Normal UWP Applications do not seem to fail like this.

**Comment by jdsterli** [comment]
Has there been any progress made on this issue?

**Comment by marb2000** [comment]
Per some local test, this is no longer an issue. it was fixed within the latest bits of the Windows Community Toolkit XAML Islands helpers.
