### ISSUE TITLE
GetClientRect instead of GetWindowRect in standalone win32 example

### ISSUE THREAD

**Issue by thomasbarker** [microsoft/Xaml-Islands-Samples#8]
I think you meant to use GetClientRect instead of GetWindowRect in the below file.
Otherwise the RECT is oversized and the sizing controls on the right and bottom will not function.

Xaml-Islands-Samples/Standalone_Samples/CppWinRT_Desktop_Win32App/DesktopWin32App/DesktopWin32App.cpp

**Comment by marb2000** [comment]
Thanks @thomasbarker for the the recommendation. The sample was removed. Please follow up other samples. Thanks!
